import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import useSWR, { Fetcher } from 'swr';

type dataType = [
  {
    id: number,
    name: string,
    brand: string,
    description: string,
    price: number,
    imageUrl: string,
    quantityInStock: number,
    type: string,
  }
]

const fetcher: Fetcher<dataType, string> = (...args) => fetch(...args).then((res) => res.json())


const Home: NextPage = () => {
  const { data, error } = useSWR('http://localhost:5285/Products', fetcher)

  // useEffect(() => {
  //   if (data) console.log(data);
  // }, [data]);


  return (
    <div>
      <Head>
        <title>E Commerce Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Store</h1>
        {error && <p>Failed to fetch data.</p>}
        {!error && !data && <p>Loading...</p>}
        {!!data && (
          <ul>
            {data.map(product => (
              <li key={product.id}>
                <p>{product.name}</p>
              </li>
              ),
            )}
          </ul>)
        }
      </main>
    </div>
  )
}

export default Home;
